//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrypTrackerWPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrypTrackerWPF.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddToConverterMenu {
            get {
                return ResourceManager.GetString("AddToConverterMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy:.
        /// </summary>
        public static string BuyMesasge {
            get {
                return ResourceManager.GetString("BuyMesasge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string ChooseTheme {
            get {
                return ResourceManager.GetString("ChooseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured on client during processing api request..
        /// </summary>
        public static string ClientSideError {
            get {
                return ResourceManager.GetString("ClientSideError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The converter is ready, click here or go to tab.
        /// </summary>
        public static string ConvertButtonName {
            get {
                return ResourceManager.GetString("ConvertButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about convert currency..
        /// </summary>
        public static string ConvertCurrencyMessage {
            get {
                return ResourceManager.GetString("ConvertCurrencyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency converter.
        /// </summary>
        public static string CurrencyConvertWindowTitle {
            get {
                return ResourceManager.GetString("CurrencyConvertWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CurrencyName {
            get {
                return ResourceManager.GetString("CurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string CurrencySign {
            get {
                return ResourceManager.GetString("CurrencySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header &quot;Price&quot; in tables displays price in dollars even if you change localization..
        /// </summary>
        public static string DescriptionToPrice {
            get {
                return ResourceManager.GetString("DescriptionToPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Info.
        /// </summary>
        public static string DetailedInfoWindowTitle {
            get {
                return ResourceManager.GetString("DetailedInfoWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string DisplayTop {
            get {
                return ResourceManager.GetString("DisplayTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t any data downloaded, please, try again..
        /// </summary>
        public static string EmptyValueError {
            get {
                return ResourceManager.GetString("EmptyValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EngCultureDescription {
            get {
                return ResourceManager.GetString("EngCultureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a quantity!.
        /// </summary>
        public static string FieldIsNotPrice {
            get {
                return ResourceManager.GetString("FieldIsNotPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrypTracker - test project for DCT.
        /// </summary>
        public static string Greetings {
            get {
                return ResourceManager.GetString("Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signle click - select. Double click - load details. Right button click - add to converter..
        /// </summary>
        public static string MainGridTooltip {
            get {
                return ResourceManager.GetString("MainGridTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top currencies.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Change per day.
        /// </summary>
        public static string PriceChange {
            get {
                return ResourceManager.GetString("PriceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveFromConverterMenu {
            get {
                return ResourceManager.GetString("RemoveFromConverterMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetButtonName {
            get {
                return ResourceManager.GetString("ResetButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell:.
        /// </summary>
        public static string SellMessage {
            get {
                return ResourceManager.GetString("SellMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured on server, status code:.
        /// </summary>
        public static string ServerSideError {
            get {
                return ResourceManager.GetString("ServerSideError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButtonName {
            get {
                return ResourceManager.GetString("SubmitButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is loading. Please, try again..
        /// </summary>
        public static string TheDataIsLoading {
            get {
                return ResourceManager.GetString("TheDataIsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string UkrCultureDescription {
            get {
                return ResourceManager.GetString("UkrCultureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
